# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-06 12:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etms1', '0002_auto_20190506_1125'),
    ]

    operations = [
        migrations.CreateModel(
            name='Addbooking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_name', models.CharField(max_length=100)),
                ('pickup_add', models.CharField(max_length=100)),
                ('drop_add', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('time', models.DateTimeField()),
            ],
        ),
    ]
