# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-07 06:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etms1', '0003_addbooking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addbooking',
            name='date',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='addbooking',
            name='time',
            field=models.CharField(max_length=10),
        ),
    ]
