# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-07 14:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('etms1', '0006_auto_20190507_2023'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addbooking',
            name='emp_name',
        ),
    ]
