# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-08 04:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('etms1', '0007_remove_addbooking_emp_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Employee',
        ),
    ]
