# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-08 05:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etms1', '0008_delete_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='addbooking',
            name='user_name',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
